### ISSUE TITLE
Replace strings of other bundles

### ISSUE THREAD

**Issue by manzolirch** [Va1/string-replace-loader#54]
Hello, i'm using Concat Plugin (https://www.npmjs.com/package/webpack-concat-plugin) to concat files in webpack, but i need replace strings in this files.. why dont work? string replace works only a webpack entry?

**Comment by Va1** [comment]
hello,

this codebase is a loader and, therefore, works only when specified on webpack entry files, yes. i don't believe it can work with the mentioned concat plugin, as plugins play after loaders usually. you could search for a relevant replace plugin, instead of a loader, which if defined after the concat one can possibly do the job.

cheers
